### ISSUE TITLE
Error when generating data

### ISSUE THREAD

**Issue by Geek-Qi** [claireaoi/hierarchical-rule-induction#1]
When I run the above code according to the documentation, the error is as follows:
Trainable params 1284
Start training for 4000 iterations with 9 constants 
Traceback (most recent call last):
  File "HRI/Grandparent.py", line 47, in <module>
    exp.run()
  File "/Users/weed/PycharmProjects/hierarchical-rule-induction/HRI/utils/Learn.py", line 167, in run
    train_acc_rate, embeddings_temporal, unifs_temporal, losses, valuation, unifs, train_iters = model.train(
  File "/Users/weed/PycharmProjects/hierarchical-rule-induction/HRI/utils/coreModel.py", line 378, in train
    valuation_init, target = self.data_generator.getData(
  File "/Users/qiyucheng/weed/hierarchical-rule-induction/HRI/utils/Dataset.py", line 53, in getData
    relations = randomly_generate_family(num_constants, 
  File "/Users/weed/PycharmProjects/hierarchical-rule-induction/HRI/utils/Family.py", line 172, in randomly_generate_family
    parents = random.choice(couples)
  File "mtrand.pyx", line 920, in numpy.random.mtrand.RandomState.choice
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

**Comment by claireaoi** [comment]
I apologize for the delay.

Unfortunately I can not reproduce the error, could you tell me more about your setup? It could be due to a library issue.

I now tested it with python 3.9.7
numpy==1.23.0
torch==1.12.0
torchtext==0.13.0

(alternatively you can use more recent versions for instance
torch==2.1.2
torchtext==0.16.2, I tried also)

Are you using a command like:
python HRI/Grandparent.py --num_iters=4000 --num_runs=2 --recursivity=full --max_depth=4 --num_feat=0 --use_gpu=False
